In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import datetime
import warnings


from scipy import stats
from itertools import product

In [2]:
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
data = pd.read_csv('kshen.txt', ';')

In [4]:
data

,Unnamed: 0,year,day,tavg,tmin,tmax,wind,sunhours,globrad,precip,relhumid
0,0,2011,1,-3.369167,-5.51,-1.11,4.349167,-1,1.951521,5.046430,0.849167
1,1,2011,2,-1.874167,-3.32,-1.11,5.057917,-1,2.051986,0.663970,0.844583
2,2,2011,3,-2.973333,-5.53,-1.11,2.768333,-1,2.418889,0.219999,0.839583
3,3,2011,4,-4.793750,-7.09,-2.78,3.062273,-1,1.089766,4.317336,0.938750
4,4,2011,5,-10.151250,-12.45,-7.22,5.175417,-1,2.813004,0.142632,0.860833
...,...,...,...,...,...,...,...,...,...,...,...
1821,1821,2015,361,-0.182083,-3.89,2.78,6.585833,-1,2.123993,0.490057,0.731667
1822,1822,2015,362,-6.087917,-8.89,-3.89,4.256250,-1,2.899156,0.000000,0.735000
1823,1823,2015,363,-7.438750,-10.00,-3.89,3.807917,-1,3.433202,0.080574,0.695417
1824,1824,2015,364,-8.530417,-9.41,-7.22,3.731667,-1,2.725277,0.266196,0.748750
1825,1825,2015,365,-10.928333,-12.78,-8.09,2.652917,-1,1.673993,0.544298,0.827917

In [5]:
def parser(year, day):
    return datetime.datetime(int(year), 1, 1) + datetime.timedelta(int(day) - 1)

In [6]:
data['date'] = data.apply(lambda x: parser(x['year'], x['day']), axis=1)

In [7]:
def data_parser(dataframe, column, idx):
    tmp = dataframe[['date', column]]
    tmp = tmp.groupby(pd.Grouper(key='date', axis=0, freq=f'{idx}')).mean()
    tmp.to_csv(f'data/{column}/full_{idx}.csv')
    tmp[tmp.index.year != 2015].to_csv(f'data/{column}/train_{idx}.csv')
    tmp[tmp.index.year == 2015].to_csv(f'data/{column}/test_{idx}.csv')

In [8]:
days = ['1d', '5d', '10d', '15d', 'M']
columns = ['tavg', 'tmin', 'tmax', 'wind', 'sunhours', 'globrad', 'precip', 'relhumid']
for day in days:
    for col in columns:
        data_parser(data, col, day)